name: The EARs Reviewing bot for PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
    paths:
      - "Assembly_Reports/**/*.pdf"

concurrency:
  group: ear-bot
  cancel-in-progress: false

jobs:
  add-label-and-find-supervisor:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 917566
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: "ERGA-consortium"
          repositories: "EARs"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: "main"
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv pip install -r ear_bot/requirements.txt

      - name: Run python script to find a reviewer
        env:
          GITHUB_APP_TOKEN: ${{ steps.generate-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          ACTION_TYPE: ${{ github.event.action }}
        run: python -u ear_bot/ear_bot_reviewer.py --supervisor
